### ISSUE TITLE
Crash ( I write here, because I don't like templates )

### ISSUE THREAD

**Issue by Kasia1403** [Gilded-Games/The-Aether-II#176] opened 2022-11-21 09:18 UTC
https://paste.ee/p/rAsOo

**Comment by Kasia1403** [comment] 2022-11-21 10:55
Whyyy nobody answers ? :(

**Comment by Aethyus** [comment] 2022-11-21 21:19
Hi. Bconlon already told you about this, that anything in the 1.12.2 mod will be fixed. The mod port will be straight to the recent game versions. So it's basically useless to report issues here. If you want help for your issues with the mod, please visit the Aether's Discord server and ask for help in the appropriate channel.

**Comment by bconlon1** [comment] 2022-11-21 21:23
Probably a mod conflict caused by a mixin conflict, can't do much except suggest removing mods until the crashing stops.

**Closed by bconlon1** 2022-11-21 21:23 UTC

**Comment by Kasia1403** [comment] 2022-11-22 09:44
Eh, it is a bit complicated. It turned out that this crash is because Universaal Tweaks mod is incompatible with Surge mod. But I don't understand why Minecraft points to Aether II instead Surge and / or Universal Tweaks.
